title: Sito-ITA
email: pfrancecsop252@gmail.com
description: >-
    
baseurl: ""
url: ""

kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-feed

photos:
  photo_repo: "s7uck/photos"
  output_url: "photos"
  ## UNCOMMENT FOR TESTING
  #remote_exif_url: "https://pastebin.com/raw/DsAnyFKz"

defaults:
  - scope:
      path: ""
    values:
      links:
        links_out: "/links-out"
        foto: "/gallery"
        contatti: "/contatti"
